### ISSUE TITLE
compat-options allow-unsafe-ext errors yt-dlp

### ISSUE THREAD

**Issue by jouven** [yt-dlp/yt-dlp#16919]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766), [the FAQ](https://github.com/yt-dlp/yt-dlp/wiki/FAQ), and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue%20-label%3Aspam%20%20) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [policy against AI/LLM contributions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#automated-contributions-ai--llm-policy) and understand I may be blocked from the repository if it is violated

### Provide a description that is worded well enough to be understood

Additional yt-dlp nightly log
`yt-dlp_night -v -f 244+251 https://www.youtube.com/watch?v=m9xqO9kKqyk
[debug] Command-line config: ['-v', '-f', '244+251', 'https://www.youtube.com/watch?v=m9xqO9kKqyk']
[debug] User config "/home/user/.config/yt-dlp/config": ['--hls-split-discontinuity', '--socket-timeout', '10', '-r', '15M', '-R', '100', '-P', 'temp:./tmp', '--fixup', 'never', '--concat-playlist', 'never', '--cookies-from-browser', 'chromium', '--compat-options', 'allow-unsafe-ext', '--xattrs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2026.06.09.230517 from yt-dlp/yt-dlp-nightly-builds [821bef0f0] (zip)
[debug] Compatibility options: allow-unsafe-ext
[debug] Python 3.14.5 (CPython x86_64 64bit) - Linux-7.0.12-lqx1-1-lqx-x86_64-with-glibc2.43 (OpenSSL 3.6.3 9 Jun 2026, glibc 2.43)
[debug] exe versions: ffmpeg 8.1.1 (setts), ffprobe 8.1.1, rtmpdump 2.6
[debug] Optional libraries: Cryptodome-3.23.0, brotlicffi-1.2.0.1, certifi-2026.05.20, curl_cffi-0.15.0, requests-2.34.2, secretstorage-3.5.0, sqlite3-3.53.2, urllib3-2.7.0, websockets-16.0, yt_dlp_ejs-0.8.0
[debug] JS runtimes: deno-2.8.2
[debug] Proxy map: {}
Extracting cookies from chromium
[debug] Extracting cookies from: "/home/user/.config/chromium/Default/Cookies"
Extracted 2377 cookies from chromium
[debug] cookie version breakdown: {'v10': 2435, 'v11': 0, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: uncensored (KnownPiracyIE)
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/my/yt_dlp_plugins
WARNING: Using allow-unsafe-ext opens you up to potential attacks. Use with great care!
[debug] Loaded 1739 extractors
[debug] [youtube] Found YouTube account cookies
[debug] [youtube] [pot] PO Token Providers: none
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[debug] [youtube] [jsc] JS Challenge Providers: bun (unavailable), deno, node (unavailable), quickjs (unavailable)
[youtube] Extracting URL: https://www.youtube.com/watch?v=m9xqO9kKqyk
[youtube] m9xqO9kKqyk: Downloading webpage
[debug] [youtube] Forcing "main" player JS variant for player 69e2a55d
        original url = /s/player/69e2a55d/player_es6.vflset/en_US/base.js
[youtube] m9xqO9kKqyk: Downloading tv downgraded player API JSON
[debug] [youtube] m9xqO9kKqyk: Detected a 15s ad for web_safari
[debug] Loading youtube-sigfuncs.69e2a55d-main-107 from cache
[debug] Loading youtube-sigfuncs.69e2a55d-main-103 from cache
[youtube] m9xqO9kKqyk: Downloading player 69e2a55d-main
[youtube] [jsc:deno] Solving JS challenges using deno
[debug] [youtube] [jsc:deno] Using challenge solver lib script v0.8.0 (source: python package, variant: minified)
[debug] [youtube] [jsc:deno] Using challenge solver core script v0.8.0 (source: python package, variant: minified)
[debug] [youtube] [jsc:deno] Running deno: /usr/bin/deno run --ext=js --no-code-cache --no-prompt --no-remote --no-lock --node-modules-dir=none --no-config --no-npm --cached-only -
[debug] [youtube] m9xqO9kKqyk: Detected experiment to bind GVS PO Token to video ID for web_safari client
[youtube] m9xqO9kKqyk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] m9xqO9kKqyk: Downloading 1 format(s): 244+251
ERROR: validate_options.<locals>.<lambda>() got an unexpected keyword argument '_allowed_exts'
Traceback (most recent call last):
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 1726, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 1882, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 1941, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 3124, in process_video_result
    self.process_info(new_info)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 3378, in process_info
    self.prepare_filename(info_dict, 'description')) is None:
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 1556, in prepare_filename
    filename = self._prepare_filename(info_dict, tmpl_type=dir_type, outtmpl=outtmpl)
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/bin/yt-dlp_night/yt_dlp/YoutubeDL.py", line 1538, in _prepare_filename
    filename = replace_extension(filename, force_ext, info_dict.get('ext'))
  File "/home/user/bin/yt-dlp_night/yt_dlp/utils/_utils.py", line 2153, in _change_extension
    return f'{filename}.{_UnsafeExtensionError.sanitize_extension(ext, _allowed_exts=_allowed_exts)}'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: validate_options.<locals>.<lambda>() got an unexpected keyword argument '_allowed_exts'`

Also the README.md section about compat-options doesn't reflect what's really in the current version, i.e., --compat-options youtube-dl and --compat-options youtube-dlc do not include allow-unsafe-ext as the readme says.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '244+251', 'https://www.youtube.com/watch?v=m9xqO9kKqyk']
[debug] User config "/home/user/.config/yt-dlp/config": ['--hls-split-discontinuity', '--socket-timeout', '10', '-r', '15M', '-R', '100', '-P', 'temp:./tmp', '--fixup', 'never', '--concat-playlist', 'never', '--cookies-from-browser', 'chromium', '--compat-options', 'allow-unsafe-ext', '--xattrs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.06.09 from yt-dlp/yt-dlp [821bef0f0]
[debug] Compatibility options: allow-unsafe-ext
[debug] Python 3.14.5 (CPython x86_64 64bit) - Linux-7.0.12-lqx1-1-lqx-x86_64-with-glibc2.43 (OpenSSL 3.6.3 9 Jun 2026, glibc 2.43)
[debug] exe versions: ffmpeg 8.1.1 (setts), ffprobe 8.1.1, rtmpdump 2.6
[debug] Optional libraries: Cryptodome-3.23.0, brotlicffi-1.2.0.1, certifi-2026.05.20, curl_cffi-0.15.0, requests-2.34.2, secretstorage-3.5.0, sqlite3-3.53.2, urllib3-2.7.0, websockets-16.0, yt_dlp_ejs-0.8.0
[debug] JS runtimes: deno-2.8.2
[debug] Proxy map: {}
Extracting cookies from chromium
[debug] Extracting cookies from: "/home/user/.config/chromium/Default/Cookies"
Extracted 2377 cookies from chromium
[debug] cookie version breakdown: {'v10': 2435, 'v11': 0, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: uncensored (KnownPiracyIE)
[debug] Plugin directories: /home/user/.config/yt-dlp/plugins/my/yt_dlp_plugins
WARNING: Using allow-unsafe-ext opens you up to potential attacks. Use with great care!
[debug] Loaded 1739 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2026.06.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2026.06.09 from yt-dlp/yt-dlp)
[debug] [youtube] Found YouTube account cookies
[debug] [youtube] [pot] PO Token Providers: none
[debug] [youtube] [pot] PO Token Cache Providers: memory
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo
[debug] [youtube] [jsc] JS Challenge Providers: bun (unavailable), deno, node (unavailable), quickjs (unavailable)
[youtube] Extracting URL: https://www.youtube.com/watch?v=m9xqO9kKqyk
[youtube] m9xqO9kKqyk: Downloading webpage
[debug] [youtube] Forcing "main" player JS variant for player 69e2a55d
        original url = /s/player/69e2a55d/player_es6.vflset/en_US/base.js
[youtube] m9xqO9kKqyk: Downloading tv downgraded player API JSON
[debug] [youtube] m9xqO9kKqyk: Detected a 15s ad for web_safari
[debug] Loading youtube-sigfuncs.69e2a55d-main-107 from cache
[debug] Loading youtube-sigfuncs.69e2a55d-main-103 from cache
[youtube] m9xqO9kKqyk: Downloading player 69e2a55d-main
[youtube] [jsc:deno] Solving JS challenges using deno
[debug] [youtube] [jsc:deno] Using challenge solver lib script v0.8.0 (source: python package, variant: minified)
[debug] [youtube] [jsc:deno] Using challenge solver core script v0.8.0 (source: python package, variant: minified)
[debug] [youtube] [jsc:deno] Running deno: /usr/bin/deno run --ext=js --no-code-cache --no-prompt --no-remote --no-lock --node-modules-dir=none --no-config --no-npm --cached-only -
[debug] [youtube] m9xqO9kKqyk: Detected experiment to bind GVS PO Token to video ID for web_safari client
[youtube] m9xqO9kKqyk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] m9xqO9kKqyk: Downloading 1 format(s): 244+251
ERROR: validate_options.<locals>.<lambda>() got an unexpected keyword argument '_allowed_exts'
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 1726, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 1882, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 1941, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 3124, in process_video_result
    self.process_info(new_info)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 3378, in process_info
    self.prepare_filename(info_dict, 'description')) is None:
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 1556, in prepare_filename
    filename = self._prepare_filename(info_dict, tmpl_type=dir_type, outtmpl=outtmpl)
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.14/site-packages/yt_dlp/YoutubeDL.py", line 1538, in _prepare_filename
    filename = replace_extension(filename, force_ext, info_dict.get('ext'))
  File "/usr/lib/python3.14/site-packages/yt_dlp/utils/_utils.py", line 2153, in _change_extension
    return f'{filename}.{_UnsafeExtensionError.sanitize_extension(ext, _allowed_exts=_allowed_exts)}'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: validate_options.<locals>.<lambda>() got an unexpected keyword argument '_allowed_exts'
```

**Comment by bashonly** [comment]
Confirmed to be a regression introduced in e578e265f7c6ca94a74b30e0d8d6196a4d19fb6a
