### ISSUE TITLE
WebSocketsWrapper error when trying to download from FC2 Live

### ISSUE THREAD

**Issue by weihenglim** [yt-dlp/yt-dlp#3422]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Downloading of streams from https://live.fc2.com/ broke with the latest version of yt-dlp. The FC2 Live extractor was working in the  2022.03.08.1 release, albeit it [required a workaround](https://github.com/yt-dlp/yt-dlp/issues/3142#issuecomment-1073724174). 

The program now throws a `'WebSocketsWrapper' object has no attribute 'pool'` error, I have the verbose logs pasted below.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://live.fc2.com/10323104/', '--add-header', 'Accept-Encoding:gzip, deflate']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106355-ga24e6ca8bf-20220320 (setts), ffprobe N-106355-ga24e6ca8bf-20220320
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [fc2:live] Extracting URL: https://live.fc2.com/10323104/
[fc2:live] 10323104: Downloading webpage
[fc2:live] 10323104: Requesting member info
[fc2:live] 10323104: Downloading ControlServer data
[fc2:live] 10323104: Fetching HLS playlist info via WebSocket
ERROR: 'WebSocketsWrapper' object has no attribute 'pool'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\fc2.py", line 209, in _real_extract
  File "yt_dlp\utils.py", line 5489, in __init__
  File "yt_dlp\utils.py", line 5493, in __enter__
AttributeError: 'WebSocketsWrapper' object has no attribute 'pool'
```

**Comment by weihenglim** [comment]
Did some quick tests and that does seems to fix the issue. Thanks.

**Comment by Lesmiscore** [comment]
@pukkandan Yes, it does
