### ISSUE TITLE
Instagram stories appear broken. Every attempt is throwing "AttributeError: 'NoneType' object has no attribute 'format'" error 

### ISSUE THREAD

**Issue by dmattera** [yt-dlp/yt-dlp#7380]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Since updating to 2023.06.21, this error has started occuring on all attempts to download instagram stories.

Based on the call stack, it seems to be the new `--netrc-cmd` option (https://github.com/yt-dlp/yt-dlp/pull/6682) is what's causing the issue as it's not being setup properly. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.instagram.com/stories/daviddobrik/3129982206290353803/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4] (pip)
[debug] Python 3.9.0 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-106844-g0a58fdfd3e-tessus (setts), ffprobe N-106844-g0a58fdfd3e-tessus
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1, xattr-0.9.9
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urlopen error [Errno 64] Host is down>); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
ERROR: 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 705, in extract
    self.initialize()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 609, in initialize
    username, password = self._get_login_info()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1335, in _get_login_info
    username, password = self._get_netrc_login_info(netrc_machine)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1300, in _get_netrc_login_info
    cmd = self.get_param('netrc_cmd', '').format(netrc_machine)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by dmattera** [comment]
Forgot to mention, I have tried multiple stories and have also tried with and without cookies, all to the same result

**Comment by dmattera** [comment]
From what it looks like, this new `netrc-cmd` option works as expected but this flaw in the new code's logic is breaking any attempts to run yt-dlp *without* the `netrc-cmd` 

when the netrc-cmd is not invoked, it causes `self.get_param('netrc_cmd', '')` in `common.py` to return as None and so you need to check it is not None before doing the `.format()` on it


```
 def _get_netrc_login_info(self, netrc_machine=None):
        netrc_machine = netrc_machine or self._NETRC_MACHINE

        **cmd = self.get_param('netrc_cmd', '').format(netrc_machine)**
        
        if cmd:
            self.to_screen(f'Executing command: {cmd}')
            stdout, _, ret = Popen.run(cmd, text=True, shell=True, stdout=subprocess.PIPE)
            if ret != 0:
                raise OSError(f'Command returned error code {ret}')
            info = netrc_from_content(stdout).authenticators(netrc_machine)
```

should be changed to something like this

```
 def _get_netrc_login_info(self, netrc_machine=None):
        netrc_machine = netrc_machine or self._NETRC_MACHINE

        **cmd = self.get_param('netrc_cmd', '')**

        if cmd:
            formatted_cmd = cmd.format(netrc_machine)
            self.to_screen(f'Executing command: {formatted_cmd}')
            stdout, _, ret = Popen.run(formatted_cmd, text=True, shell=True, stdout=subprocess.PIPE)
            if ret != 0:
                raise OSError(f'Command returned error code {ret}')
            info = netrc_from_content(stdout).authenticators(netrc_machine)
```

**Comment by bashonly** [comment]
You're right about the issue; it was also fixed in d7cd97e8d8d42b500fea9abb2aa4ac9b0f98b2ad. It will be fixed in next release. Glad you found a solution, although if you don't want to run modified source, you can [install from master with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master), or use the workaround of adding `--netrc-cmd ""` to your commands/config

Closing as duplicate of #7367
