### ISSUE TITLE
drtv broken on 2023.01.06. 2022.11.11 works.

### ISSUE THREAD

**Issue by henrik-jensen** [yt-dlp/yt-dlp#6046]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Denmark

### Provide a description that is worded well enough to be understood

OS: Microsoft Windows [Version 10.0.19045.2486]
(Using the provided windows executable).

This is a problem that seems to affect drtv (https://www.dr.dk/drtv/) with version 2023.01.06 but not youtube.com with version 2023.01.06.
drtv also works with previous version 2022.11.11.
Attached logs from 3 different runs:
```bat
:: v2023.01.06 Fails with: ERROR: download_content() got an unexpected keyword argument 'default'
yt-dlp https://www.dr.dk/drtv/se/jexi_361691 -vU
:: v2023.01.06 succeeds downloading youtube-dl test video by Philipp Hagemeister
yt-dlp https://www.youtube.com/watch?v=BaW_jenozKc -vU
:: v2022.11.11. Succeeds. **Note!** Can't use -vU as this replaces the old version with the buggy 2023.01.06. before running!!!
yt-dlp_2022.11.11.exe https://www.dr.dk/drtv/se/jexi_361691 -v
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
--------------------------------------------------------------------------------------------------
:: v2023.01.06 Fails with: ERROR: download_content() got an unexpected keyword argument 'default':
--------------------------------------------------------------------------------------------------
> yt-dlp https://www.dr.dk/drtv/se/jexi_361691 -vU
[debug] Command-line config: ['https://www.dr.dk/drtv/se/jexi_361691', '-vU']
[debug] User config "C:\Users\henrik\AppData\Roaming\yt-dlp\config": ['--write-info-json', '--no-abort-on-error', '--ignore-errors']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'no': '192.168.99.100'}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[drtv] Extracting URL: https://www.dr.dk/drtv/se/jexi_361691
[drtv] jexi_361691: Downloading webpage
[drtv] 00022130820: Downloading video JSON
ERROR: download_content() got an unexpected keyword argument 'default'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\drtv.py", line 187, in _real_extract
TypeError: download_content() got an unexpected keyword argument 'default'

---------------------------------------------------------------------------------
:: v2023.01.06 succeeds downloading youtube-dl test video by Philipp Hagemeister:
---------------------------------------------------------------------------------
> yt-dlp https://www.youtube.com/watch?v=BaW_jenozKc -vU
[debug] Command-line config: ['https://www.youtube.com/watch?v=BaW_jenozKc', '-vU']
[debug] User config "C:\Users\henrik\AppData\Roaming\yt-dlp\config": ['--write-info-json', '--no-abort-on-error', '--ignore-errors']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'no': '192.168.99.100'}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[info] Writing video metadata as JSON to: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].info.json
[debug] Invoking http downloader on "https://rr3---sn-4pcxgct-j2ie.googlevideo.com/videoplayback?expire=1673922531&ei=g7PFY8vIJdjEgAf717fwCw&ip=89.23.233.77&id=o-AMbk8qmM50J4HUCimSFLrxYVyjQIBf4ofLtw8vI2J_XX&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-4pcxgct-j2ie%2Csn-5hneknek&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1767500&spc=zIddbIprWtjBAnxrR0bYi60J4tlVv5U&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1673900736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIuc-4BlQEVmxVxmpzQ4ALbjtBlXO3e6wnD6jcSufeSUCIQCdA6ChrvnETpDUhMMIz1gepaH91m-OAXY-Sy93gQzPNA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPG-_YzaT89t6DGJtgbGCU4WyVei76H2EtFmtB43ngA8CIEd1p3V053vjdVmisCzxfo4hAenRhNsyXvgogofp8nFw"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm
[download] 100% of  965.31KiB in 00:00:00 at 11.13MiB/s
[debug] Invoking http downloader on "https://rr3---sn-4pcxgct-j2ie.googlevideo.com/videoplayback?expire=1673922531&ei=g7PFY8vIJdjEgAf717fwCw&ip=89.23.233.77&id=o-AMbk8qmM50J4HUCimSFLrxYVyjQIBf4ofLtw8vI2J_XX&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-4pcxgct-j2ie%2Csn-5hneknek&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1767500&spc=zIddbIprWtjBAnxrR0bYi60J4tlVv5U&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1673900736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALfDcpwpgWgvLuBulPtFmAaa40U3RHxEtk4BjWesQf3FAiEA2N7z-STjpXdx5aJVMy0nQKhlzDHB7IwfahYmlQRADx0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPG-_YzaT89t6DGJtgbGCU4WyVei76H2EtFmtB43ngA8CIEd1p3V053vjdVmisCzxfo4hAenRhNsyXvgogofp8nFw"
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm
[download] 100% of  138.96KiB in 00:00:00 at 4.34MiB/s
[Merger] Merging formats into "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm" -i "file:youtube-dl test video ＂'⧸⧹ä↭𝕐 [Ba
W_jenozKc].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].temp.webm"
Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm (pass -k to keep)
Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm (pass -k to keep)

--------------------------------------------------------------------------------------------------------------------------------
:: v2022.11.11. Succeeds. **Note!** Can't use -vU as this replaces the old version with the buggy 2023.01.06. before running!!!:
--------------------------------------------------------------------------------------------------------------------------------
> yt-dlp_2022.11.11.exe https://www.dr.dk/drtv/se/jexi_361691 -v
[debug] Command-line config: ['https://www.dr.dk/drtv/se/jexi_361691', '-v']
[debug] User config "C:\Users\henrik\AppData\Roaming\yt-dlp\config": ['--write-info-json', '--no-abort-on-error', '--ignore-errors']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'no': '192.168.99.100'}
[debug] Loaded 1723 extractors
[debug] [drtv] Extracting URL: https://www.dr.dk/drtv/se/jexi_361691
[drtv] jexi_361691: Downloading webpage
[drtv] 00022130820: Downloading video JSON
[drtv] 00022130820: Downloading m3u8 information
WARNING: [drtv] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[drtv] 00022130820: Downloading m3u8 information
[drtv] 00022130820: Downloading m3u8 information
[drtv] 00022130820: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 00022130820: Downloading 1 format(s): HLS-5849
[info] Writing video metadata as JSON to: Jexi [00022130820].info.json
[debug] Invoking hlsnative downloader on "https://drod20g.akamaized.net/dk/clear/none/7d/63b8f692ac5a623f70816f7d/00022130820/stream_ts/Jexi-Jexi_DRTV2022Jan_HD_16x9_VideoMain_5500.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 467
[download] Destination: Jexi [00022130820].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    3.18GiB in 00:01:09 at 46.84MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Jexi [00022130820].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Jexi [00022130820].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Jexi [00022130820].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Jexi [00022130820].temp.mp4"
```

**Comment by bashonly** [comment]
This issue has been fixed in the master branch (7481998b169b2a52049fc33bff82034d6563ead4). If you don't want to wait for the next release, you can [install from master with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or try the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

Closing as duplicate of #5993
