### ISSUE TITLE
DRTV download failed

### ISSUE THREAD

**Issue by zettimetti** [yt-dlp/yt-dlp#5993]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Download working fine with 2023.01.02 but not with 2023.01.06

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\FFmpeg>youtube-dl --verbose "https://www.dr.dk/drtv/se/fredagstamtam_357148"
[debug] Command-line config: ['--verbose', 'https://www.dr.dk/drtv/se/fredagstamtam_357148']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-01-04-git-4a80db5fc2-full_build-www.gyan.dev (setts), ffprobe 2023-01-04-git-4a80db5fc2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[drtv] Extracting URL: https://www.dr.dk/drtv/se/fredagstamtam_357148
[drtv] fredagstamtam_357148: Downloading webpage
[drtv] 00922305010: Downloading video JSON
ERROR: download_content() got an unexpected keyword argument 'default'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\drtv.py", line 187, in _real_extract
TypeError: download_content() got an unexpected keyword argument 'default'


C:\FFmpeg>pause
Press any key to continue . . .
```

**Comment by bashonly** [comment]
something like this should fix it, I'm geo-blocked and can't test it, though

```diff
diff --git a/yt_dlp/extractor/drtv.py b/yt_dlp/extractor/drtv.py
index d3e197551..470546bbc 100644
--- a/yt_dlp/extractor/drtv.py
+++ b/yt_dlp/extractor/drtv.py
@@ -184,9 +184,10 @@ def _real_extract(self, url):
         data = self._download_json(
             programcard_url, video_id, 'Downloading video JSON', query=query)
 
-        supplementary_data = self._download_json(
-            SERIES_API % f'/episode/{raw_video_id}', raw_video_id,
-            default={}) if re.search(r'_\d+$', raw_video_id) else {}
+        supplementary_data = {}
+        if re.search(r'_\d+$', raw_video_id):
+            supplementary_data = self._download_json(
+                SERIES_API % f'/episode/{raw_video_id}', raw_video_id, fatal=False) or {}
 
         title = str_or_none(data.get('Title')) or re.sub(
             r'\s*\|\s*(?:TV\s*\|\s*DR|DRTV)$', '',
```

**Comment by hchr** [comment]
@bashonly 
Works again with the patch, thank you

[drtv] Extracting URL: https://www.dr.dk/drtv/se/tv-avisen_-bolsonaro_tilhaengere-stormer-den-brasilianske-kongres_360776
[drtv] tv-avisen_-bolsonaro_tilhaengere-stormer-den-brasilianske-kongres_360776: Downloading webpage
[drtv] 00122304050: Downloading video JSON
[drtv] tv-avisen_-bolsonaro_tilhaengere-stormer-den-brasilianske-kongres_360776: Downloading JSON metadata
[drtv] 00122304050: Downloading m3u8 information
[drtv] 00122304050: Downloading m3u8 information
[info] 00122304050: Downloading 1 format(s): HLS-5862
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 88
