### ISSUE TITLE
Odysee/LBRY broken

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#4176]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Unable to download videos - unable to download json info

This is inconsistent with different videos, but on several videos it's consistently failing with version `2022.06.22.1`, and consistently working with version `2022.05.18`.

The below examples use `-F` for brevity, but I'm getting the same results with `-j`, `--dump-json`, and `-J` `--dump-single-json`, and just trying to download the videos.

Using the older version `2022.05.18`:
Command line: `yt-dlp -v  --ignore-config -F 'https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c'`
Output:
```
[debug] Command-line config: ['-v', '--ignore-config', '-F', 'https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-120-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, mutagen-1.45.1, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [lbry] Extracting URL: https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading stream JSON metadata
[lbry] c18e9ac0ffbd6ea4518f20d79a85734b04b5a092: Downloading streaming url JSON metadata
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading streaming redirect url info
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for c18e9ac0ffbd6ea4518f20d79a85734b04b5a092:
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────────────
hls-180  mp4 256x144    │ ~ 19.38MiB  180k m3u8_n │ avc1.4d400b  180k mp4a.40.2  0k
hls-655  mp4 640x360    │ ~ 70.43MiB  655k m3u8_n │ avc1.4d401e  655k mp4a.40.2  0k
hls-2890 mp4 1280x720   │ ~310.54MiB 2890k m3u8_n │ avc1.4d401f 2890k mp4a.40.2  0k
hls-4026 mp4 1920x1080  │ ~432.48MiB 4026k m3u8_n │ avc1.4d4028 4026k mp4a.40.2  0k

```

That's version `2022.05.18`, working as expected.

Try that same command with the latest version `2022.06.22.1` and it fails:
```
[debug] Command-line config: ['-v', '--ignore-config', '-F', 'https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Plugins: ['Youtube_AgeGateBypassIE']
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-120-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, mutagen-1.45.1, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [lbry] Extracting URL: https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading stream JSON metadata
[lbry] c18e9ac0ffbd6ea4518f20d79a85734b04b5a092: Downloading streaming url JSON metadata
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading streaming redirect url info
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading m3u8 information
ERROR: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/lbry.py", line 206, in _real_extract
    info['formats'] = self._extract_m3u8_formats(
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 2122, in _extract_m3u8_formats
    fmts, subs = self._extract_m3u8_formats_and_subtitles(*args, **kwargs)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 2133, in _extract_m3u8_formats_and_subtitles
    res = self._download_webpage_handle(
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 833, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 772, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 738, in _create_request
    return sanitized_Request(url_or_request, data, headers)
  File "/home/atom/bin/yt-dlp/yt_dlp/utils.py", line 766, in sanitized_Request
    return compat_urllib_request.Request(url, *args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 334, in __init__
    for key, value in headers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

nb, some videos are working fine with both versions, some videos are not working with the newer (`2022.06.22.1`) version.

So far I've only encountered problems with Odysee, but I'm not sure if it's site-specific.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--ignore-config', '-F', 'https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Plugins: ['Youtube_AgeGateBypassIE']
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-120-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, mutagen-1.45.1, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [lbry] Extracting URL: https://odysee.com/@whygoldandsilver:1/this-data-point-says-gold-prices-are-set:c
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading stream JSON metadata
[lbry] c18e9ac0ffbd6ea4518f20d79a85734b04b5a092: Downloading streaming url JSON metadata
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading streaming redirect url info
[lbry] @whygoldandsilver#1/this-data-point-says-gold-prices-are-set#c: Downloading m3u8 information
ERROR: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "/home/atom/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/lbry.py", line 206, in _real_extract
    info['formats'] = self._extract_m3u8_formats(
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 2122, in _extract_m3u8_formats
    fmts, subs = self._extract_m3u8_formats_and_subtitles(*args, **kwargs)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 2133, in _extract_m3u8_formats_and_subtitles
    res = self._download_webpage_handle(
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 833, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 772, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/atom/bin/yt-dlp/yt_dlp/extractor/common.py", line 738, in _create_request
    return sanitized_Request(url_or_request, data, headers)
  File "/home/atom/bin/yt-dlp/yt_dlp/utils.py", line 766, in sanitized_Request
    return compat_urllib_request.Request(url, *args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 334, in __init__
    for key, value in headers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by pukkandan** [comment]
Same underlying issue as #4176

**Comment by atom-smasher** [comment]
This is #4176
