### ISSUE TITLE
AttributeError: 'YoutubeDL' object has no attribute '_out_files' during VT mode init on Windows (Python 3.12)

### ISSUE THREAD

**Issue by Hiltronix** [yt-dlp/yt-dlp#12695]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766), [the FAQ](https://github.com/yt-dlp/yt-dlp/wiki/FAQ), and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue%20-label%3Aspam%20%20) for similar issues **including closed ones**. DO NOT post duplicates

### Provide a description that is worded well enough to be understood

When using yt-dlp version 2025.3.21 on Windows with Python 3.12, if `windows_enable_vt_mode()` fails (which can happen when output is redirected), the `__init__()` method crashes while trying to call `self.write_debug(...)` because `self._out_files` has not been initialized yet.

This results in an `AttributeError` inside the constructor, preventing any use of `YoutubeDL`.

### Root Cause:
In `__init__()`, `_out_files` is initialized *after* the `try/except` block calling `windows_enable_vt_mode()`. If an exception occurs, `write_debug()` is called before `_out_files` exists, which crashes the app.

### Fix:
Move the initialization of `self._out_files` above the call to `windows_enable_vt_mode()` to ensure it's always available before any debug logging happens.

```python
stdout = sys.stderr if self.params.get('logtostderr') else sys.stdout
self._out_files = Namespace(
    out=stdout,
    error=sys.stderr,
    screen=sys.stderr if self.params.get('quiet') else stdout,
    console=next(filter(supports_terminal_sequences, (sys.stderr, sys.stdout)), None),
)

try:
    windows_enable_vt_mode()
except Exception as e:
    self.write_debug(f'Failed to enable VT mode: {e}')
```

I manually reordered the code in my local install and it solved the issue.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Here is a section of my log file with verbose set to True.


OSError: [Errno 9] Bad file descriptor: 'CONOUT$'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Development\Python Scripts\VideoDownloader\YouTubeExtras.py", line 278, in GetYouTubeVideoMetaData
    with yt_dlp.YoutubeDL(opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 660, in __init__
    self.write_debug(f'Failed to enable VT mode: {e}')
  File "D:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1119, in write_debug
    self.to_stderr(message, only_once)
  File "D:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 967, in to_stderr
    self._write_string(f'{self._bidi_workaround(message)}\n', self._out_files.error, only_once=only_once)
                                                              ^^^^^^^^^^^^^^^
AttributeError: 'YoutubeDL' object has no attribute '_out_files'

2025-03-22 07:32:18,YouTubeExtras,DEBUG,Func:GetYouTubeVideoMetaData,Exception! AttributeError: 'YoutubeDL' object has no attribute '_out_files'
Traceback (most recent call last):
  File "D:\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 658, in __init__
    windows_enable_vt_mode()
  File "D:\Python312\Lib\site-packages\yt_dlp\utils\_utils.py", line 4794, in windows_enable_vt_mode
    handle = os.open('CONOUT$', os.O_RDWR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bashonly** [comment]
regression introduced in f7a1f2d8132967a62b0f6d5665c6d2dde2d42c09
