### ISSUE TITLE
[Twitter] ERROR: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by JunkFood02** [yt-dlp/yt-dlp#7367]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Probably a "regression" issue because it works on previous releases

Original reported on https://github.com/JunkFood02/Seal/issues/878 by @ayesc9000

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://twitter.com/EverythingOOC/status/1671088492095348738
[debug] Command-line config: ['-vU', 'https://twitter.com/EverythingOOC/status/1671088492095348738']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4] (pip)
[debug] Python 3.9.16 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.21, Current version: stable@2023.06.21
yt-dlp is up to date (stable@2023.06.21)
ERROR: 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 705, in extract
    self.initialize()
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 609, in initialize
    username, password = self._get_login_info()
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1335, in _get_login_info
    username, password = self._get_netrc_login_info(netrc_machine)
  File "/opt/homebrew/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1300, in _get_netrc_login_info
    cmd = self.get_param('netrc_cmd', '').format(netrc_machine)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by fireattack** [comment]
Regression caused by https://github.com/yt-dlp/yt-dlp/commit/db3ad8a67661d7b234a6954d9c6a4a9b1749f5eb

**Comment by pukkandan** [comment]
I'll make a quick-fix release soon. Till then, use `--netrc-cmd ""` as workaround.

**Comment by antdude** [comment]
FYI. Vimeo has this issue too as shown in my https://www.reddit.com/r/youtubedl/comments/14fddtl/unable_to_download_this_vimeo_video_on_two/ post. I was told this issue was related to this bug.

**Comment by alamir12** [comment]
I hope to translate this location to Arabic language

**Comment by elhaddade** [comment]
Error
