### ISSUE TITLE
Error After Updating to yt-dlp-2023.11.16 on Ubuntu Server

### ISSUE THREAD

**Issue by magicajax** [yt-dlp/yt-dlp#8712]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Issue Summary:
I'm experiencing an error with yt-dlp after updating from version 2023.09.24 to 2023.11.16 on my Ubuntu server. The previous version worked without issues, and I have not made any changes to my shell scripts.

Environment:

Operating System: Ubuntu Server
Previous yt-dlp Version: 2023.09.24
Current yt-dlp Version: 2023.11.16
python version: python3.11
Steps to Reproduce:

Update yt-dlp from version 2023.09.24 to 2023.11.16.
Run my existing shell script (./yt-dlp.sh).
Expected Behavior:
The script should run as it did with the previous yt-dlp version.

Actual Behavior:
Encountered an error when running the script with yt-dlp version 2023.11.16.

Additional Information:

The error occurs without any modifications to the script or environment.
All versions of yt-dlp after 2023.09.24 have resulted in this error.
I would appreciate any assistance or suggestions to resolve this issue. Thank you for your support.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp.sh 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1074, in _find_spec
AttributeError: '_SixMetaPathImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karapella/public_html/yt-dlp-2023.11.16 /yt-dlp-2023.11.16/yt_dlp/__main__.py", line 14, in <module>
    import yt_dlp
  File "/home/karapella/public_html/yt-dlp-2023.11.16 /yt-dlp-2023.11.16/yt_dlp/__init__.py", line 19, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "/home/karapella/public_html/yt-dlp-2023.11.16 /yt-dlp-2023.11.16/yt_dlp/cookies.py", line 21, in <module>
    from .aes import (
  File "/home/karapella/public_html/yt-dlp-2023.11.16 /yt-dlp-2023.11.16/yt_dlp/aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File "/home/karapella/public_html/yt-dlp-2023.11.16 /yt-dlp-2023.11.16/yt_dlp/dependencies/__init__.py", line 62, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1076, in _find_spec
  File "<frozen importlib._bootstrap>", line 1049, in _find_spec_legacy
ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
```

**Comment by magicajax** [comment]
thank you for replying.
download a binary -> locate the folder [Source code(tar.gz)] -> extract it and run ./yt-dlp.sh 
as i mentioned its all worked fine with the [yt-dlp 2023.09.24] [Source code(tar.gz)]  will i still need to reinstall using into a venv or use yt-dlp_linux to run it instead. Alternatively use pipx?

**Comment by magicajax** [comment]
yt-dlp_linux works for me. thank you so much for your insight
